version: '3'

services:
 mysql:
   image: mysql:5.7
   container_name: mysql-server
   ports:
     - 3306:3306
   environment:
<<<<<<< HEAD
     MYSQL_ROOT_PASSWORD: "Your passowrd"
=======
     MYSQL_ROOT_PASSWORD: "arpan"
>>>>>>> master

   volumes:
    - ./storage/docker/mysql-datadir:/var/lib/mysql
